---
# tasks file for ansible-role-minerstat

- name: add repo ppa:ubuntu-toolchain-r/test
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test

- name: add repo ppa:graphics-drivers/ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa

- name: install dependencies
  package:
    name: "{{ item }}"
  with_items:
    - git
    - screen
    - nodejs
    - nodejs-legacy
    - unzip
    - npm
    - ocl-icd-opencl-dev
    - libcurl3:i386
    - libcurl4-openssl-dev
    - libssl-dev
    - libjansson-dev
    - libpci-dev
    - libstdc++6

- name: clone minerstat-linux
  git:
    repo: https://github.com/coinscrow/minerstat-linux/
    dest: "{{ minerstat_install_path }}"
    update: no

- name: Install node.js packages
  npm:
    name: "{{ item }}"
    path: "{{ minerstat_install_path }}"
  with_items:
    - colors
    - sleep
    - pump
    - request
    - express
    - sphp
    - progress
    - ascii-text-generator
    - fkill
    - needle
    - parse-spawn-args
    - readline-sync

- name: install nvidia drivers
  package:
    name: "{{ item }}"
  with_items:
    - nvidia-cuda-toolkit
  when: gpu == "nvidia"
  notify:
    - reboot

- name: update-grub
  shell: update-grub
  when: gpu == "nvidia"

- name: nvidia-xconfig
  shell: nvidia-xconfig -s -a --allow-empty-initial-configuration --cool-bits=28 --registry-dwords="PerfLevelSrc=0x2222" --no-sli --connected-monitor="DFP-0"
  when: gpu == "nvidia"

- debug:
    msg: "AMD GPU not yet implemented by role"
  when: gpu == "amd"

- debug:
    msg: "No GPU driver installed, gpu variable has to be set"
  when: gpu != "amd" and gpu != "amd"

- name: setting owner and group of install directory
  file:
    path: "{{ minerstat_install_path }}"
    owner: "{{ minerstat_user }}"
    group: "{{ minerstat_group }}"
    recurse: yes

- name: setting permissions of ansible directory
  file:
    path: /etc/ansible
    owner: "{{ minerstat_user }}"
    group: "{{ minerstat_group }}"
    mode: g+rw
    recurse: yes
  when: set_ansible_directory_permissions

- name: configure minerstat
  template:
    src: minerstat.config.js.j2
    dest: "{{ minerstat_install_path }}/config.js"
  notify:
    - restart_minerstat

- name: add minerstat.service
  template:
    src: minerstat.service.ini.j2
    dest: /lib/systemd/system/minerstat.service
    mode: 0644
  become: yes
  notify:
    - minerstat_reload_systemd
    - restart_minerstat


- name: install nvidia toolkit 9 for ubuntu 16.04 - base installer
  apt:
    deb: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb
  when: ansible_distribution_version == '16.04'

- name: install nvidia toolkit 9 for ubuntu 16.04 - add key from developer.download.nvidia.com
  apt_key:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    state: present
  when: ansible_distribution_version == '16.04'

- name: install nvidia toolkit 9 for ubuntu 16.04 - install cuda
  apt:
    name: cuda
    update_cache: yes
  when: ansible_distribution_version == '16.04'

#- name: install nvidia toolkit 9 for ubuntu 16.04 - install cuda
#  package:
#    name: cuda
#  when: install_nvidia_toolkit_9_for_ubuntu_16_04
