---
# handlers file for ansible-role-minerstat

- name: reboot
  command: /sbin/reboot

- name: minerstat_reload_systemd
  command: systemctl daemon-reload
  become: yes

- name: restart_minerstat
  service:
    name: minerstat
    state: restarted
    enabled: yes
  become: yes
